# Generated by Django 3.2.4 on 2021-06-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('images', models.ImageField(blank=True, upload_to='images/%Y/%m/%d')),
            ],
        ),
    ]
