# Generated by Django 3.2.4 on 2021-06-03 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movies',
            table='ex01_movies',
        ),
    ]
